export const orderListMolGridData = [
  {
    id: 1,
    customerName: "Christopher Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 2,
    customerName: "test Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 3,
    customerName: "test Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 4,
    customerName: "test Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 5,
    customerName: "Christopher Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 6,
    customerName: "test Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 7,
    customerName: "test Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
  {
    id: 8,
    customerName: "test Nolan",
    poNumber: 829895144,
    paymentMethodTerms: "Inception",
    entryDatePODate: "2010-07-16",
    noItems: "1",
    totalPrice: "1252",
    status: "Active",
  },
];

export const collapsibleChildGridData = [
  // Inception
  {
    id: 1,
    catalog: "Leonardo DiCaprio",
    casNumber: "Dom Cobb",
    unitSize: "1",
    price: "12521",
    status: "Complete",
    deliveryMeter: "fkj kdsfksdh fksdfhskjd f",
    action:""
  },
  {
    id: 1,
    catalog: "Leonardo DiCaprio",
    casNumber: "Dom Cobb",
    unitSize: "1",
    price: "12521",
    status: "Complete",
    deliveryMeter: "fkj kdsfksdh fksdfhskjd f",
    action:""
  },
];
