export const Menu = [
  {
    name: "Dashboard",
    id: "Dashboard",
    to: "/",
    iconClass: "bi bi-file-earmark-medical",
    subMenu: false,
    children: [],
  },
  {
    name: "Form",
    id: "form",
    to: "/themeComponent/demoForm",
    iconClass: "bi bi-file-earmark-medical",
    subMenu: false,
    children: [],
  },
  {
    name: "Grid",
    id: "gridPage",
    to: "/themeComponent/demoGrid",
    iconClass: "bi bi-table",
    subMenu: false,
    children: [],
  },
  {
    name: "Stepper",
    id: "Stepper",
    to: "/themeComponent/stepper",
    iconClass: "bi bi-table",
    subMenu: false,
    children: [],
  },
  {
    name: "widgets",
    id: "widgets",
    to: "/themeComponent/widgets",
    iconClass: "bi bi-clipboard-data",
    subMenu: false,
    children: [],
  },
  {
    id: "dropdownSample",
    name: "Security",
    iconClass: "bi bi-shield-fill-check",
    subMenu: true,
    to: "#",
    children: [
      {
        id: "Users",
        submenuName: "User Management",
        to: "/Users",
      },
      {
        id: "roleManagement",
        submenuName: "Role Management",
        to: "/usersRole",
      },
      {
        id: "SecurityRoleManagement",
        submenuName: "Security Roles Management",
        to: "/SecurityRoleManagement",
      },
    ],
  },
  {
    id: "customer",
    name: "Customer Details",
    iconClass: "bi bi-people-fill",
    subMenu: true,
    to: "#",
    children: [
      {
        id: "addCustomer",
        submenuName: "Add Customer",
        to: "/addCustomer",
      },
      {
        id: "viewCustomer",
        submenuName: "View Customer",
        to: "/viewCustomer",
      },
    ],
  },
];
